# Generated by Django 4.2.7 on 2023-12-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("c_name", models.CharField(max_length=250)),
                ("c_email", models.EmailField(max_length=254)),
                ("c_type", models.CharField(max_length=300)),
                ("c_message", models.TextField()),
            ],
        ),
    ]
