# Generated by Django 4.2.7 on 2023-12-15 05:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AMapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="customers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("c_fname", models.CharField(max_length=350)),
                ("c_lname", models.CharField(max_length=350)),
                ("c_addr", models.TextField()),
                ("c_city", models.CharField(max_length=300)),
                ("c_mail", models.EmailField(max_length=254)),
                ("c_zip", models.IntegerField()),
                ("c_state", models.CharField(max_length=200)),
                ("c_phone", models.IntegerField()),
                ("c_cindate", models.DateField()),
                ("c_coutdate", models.DateField()),
                ("c_driver", models.IntegerField()),
                ("c_apt", models.CharField(max_length=200)),
                ("c_vtype", models.CharField(max_length=300)),
                ("c_vmod", models.CharField(max_length=250)),
                ("c_trans", models.CharField(max_length=200)),
                ("c_splints", models.TextField()),
            ],
        ),
    ]
